Repository moq-wg/moq-transport, pull requests merged in 2024-11, with the labels that each got.

#603 Remove 'Role'
  draft-ietf-moq-transport.md
Labels: Handshake

#518 Rewrite the Priority section to improve clarity
  draft-ietf-moq-transport.md
Labels: Transmission/Priority

#611 Clarify MAX_SUBSCRIBE_ID
  draft-ietf-moq-transport.md
Labels: Editorial
