Repository moq-wg/moq-transport, pull requests merged in 2024-10, with the labels that each got.

#566 fix typo
  draft-ietf-moq-transport.md
Labels: Editorial

#564 update can to MAY
  draft-ietf-moq-transport.md
Labels: Editorial

#558 Editorial update on overview of sections
  draft-ietf-moq-transport.md
Labels: Editorial

#561 clarify order of sending unsubscribe
  draft-ietf-moq-transport.md
Labels: Editorial

#516 Remove track per stream
  draft-ietf-moq-transport.md
Labels: Parked

#581 Fetch Objects if you can
  draft-ietf-moq-transport.md
Labels: Subscribe

#591 Clarify SUBSCRIBE now that FETCH is landed
  draft-ietf-moq-transport.md
Labels: Subscribe

#593 SUBSCRIBEs end at a group boundary
  draft-ietf-moq-transport.md
Labels: Subscribe
