Repository moq-wg/moq-transport, pull requests merged in 2024-12, with the labels that each got.

#627 Bidirectional goaway
  draft-ietf-moq-transport.md
Labels: Design

#626 Protocol Violation for namespace tuples outside 1..32
  draft-ietf-moq-transport.md
Labels: Editorial

#623 Datagram FETCH subgroup id=object ID
  draft-ietf-moq-transport.md
Labels: Object Model

#622 Recommend mid-range default priority
  draft-ietf-moq-transport.md
Labels: Transmission/Priority, Design

#621 Group ID and Object ID are ordered
  draft-ietf-moq-transport.md
Labels: Editorial

#620 Add an error code for Too Far Behind
  draft-ietf-moq-transport.md
Labels: Subscribe, Design

#624 Address Editorial Feedback in #218
  draft-ietf-moq-transport.md
Labels: Editorial

#637 Add AuthInfo as Fetch parameter
  draft-ietf-moq-transport.md
Labels: Parameters

#634 Separate datagram and stream ID spaces
  draft-ietf-moq-transport.md
Labels: Wire Format

#609 Do something useful with SUBSCRIBE_DONE
  draft-ietf-moq-transport.md
Labels: Design

#628 SUBSCRIBE_DONE with Stream Count
  draft-ietf-moq-transport.md
Labels: Design

#625 Remove length field from OBJECT_DATAGRAM
  draft-ietf-moq-transport.md
Labels: Wire Format, Design
