Repository moq-wg/moq-transport, pull requests merged in 2025-01, with the labels that each got.

#635 Clarify End of track
  draft-ietf-moq-transport.md
Labels: Object Model

#619 Add session errors for control and data timeout
  draft-ietf-moq-transport.md
Labels: Design

#645 Add FETCH to Relay section
  draft-ietf-moq-transport.md
Labels: Editorial

#646 Editorial changes
  draft-ietf-moq-transport.md
Labels: Editorial

#643 Message flows and endpoint state management (Was: ANNOUNCE)
  draft-ietf-moq-transport.md
Labels: Announce, Design

#647 Remove EndObject from SUBSCRIBE_UPDATE description
  draft-ietf-moq-transport.md
Labels: Editorial

#651 Object Does Not Exist not Object Not Available
  draft-ietf-moq-transport.md
Labels: Editorial

#642 Clarify multiple transport streams for Subgroups
  draft-ietf-moq-transport.md
Labels: Editorial
