Repository moq-wg/moq-transport, pull requests merged in 2025-07, with the labels that each got.

#1049 Rename SUBSCRIBE_ANNOUNCES back to SUBSCRIBE_NAMESPACE
  draft-ietf-moq-transport.md
Labels: Editorial

#1015 Make TRACK_STATUS mirror SUBSCRIBE
  draft-ietf-moq-transport.md
Labels: Wire Format, Design

#1074 PUBLISH field name consistency
  draft-ietf-moq-transport.md
Labels: Editorial

#1054 Objects are not schedulable if flow-control blocked
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#1058 Add an AUTHORITY parameter
  draft-ietf-moq-transport.md
Labels: Handshake and Session, Design

#1080 Update Subscribe ID to Request ID
  draft-ietf-moq-transport.md
Labels: Editorial

#1082 OBJECT_DATAGRAM_STATUS
  draft-ietf-moq-transport.md
Labels: Editorial

#1042 Delta encode Object IDs within Subgroups
  draft-ietf-moq-transport.md
Labels: Wire Format, Design

#1088 Update SUBGROUP_HEADER examples
  draft-ietf-moq-transport.md
Labels: Editorial

#1089 Tuple of Track Namespace and Track Name
  draft-ietf-moq-transport.md
Labels: Editorial

#1090 "currently close" -> "close"
  draft-ietf-moq-transport.md
Labels: Editorial

#1071 Indicate which params can appear PUBLISH* messages
  draft-ietf-moq-transport.md
Labels: Parameters, Editorial & Minor Design

#1102 `ContentExists` -> `Content Exists`
  draft-ietf-moq-transport.md
Labels: Editorial

#1091 Reformat Error Codes
  draft-ietf-moq-transport.md
Labels: Editorial

#1087 Explain how to resume publishing after losing state
  draft-ietf-moq-transport.md
Labels: Editorial, Merge Ready
