Repository moq-wg/moq-transport, pull requests merged in 2025-09, with the labels that each got.

#1173 Major FETCH Reorganization
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#1199 Missed error code capitalization
  draft-ietf-moq-transport.md
Labels: Editorial

#1201 Remove last OBJECT_DATAGRAM_STATUS
  draft-ietf-moq-transport.md
Labels: Editorial

#1214 PUBLISH message lengths are 16 not i
  draft-ietf-moq-transport.md
Labels: Editorial

#1192 Some editorial changes to v14
  draft-ietf-moq-transport.md
Labels: Editorial

#1207 Remove multiline [] notation for Extensions
  draft-ietf-moq-transport.md
Labels: Editorial

#1056 Make default PUBLISHER PRIORITY a parameter, optional in Subgroup/Datagram
  draft-ietf-moq-transport.md
Labels: Wire Format, Parameters, Merge Ready

#1239 Make normative text on subgroups in different streams
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design, Merge Ready
