Repository moq-wg/moq-transport, pull requests merged in 2025-04, with the labels that each got.

#822 Add error codes for Duplicate and Invalid Subscribe ID
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#813 MAX_CACHE_DURATION allowed in SUBSCRIBE_OK and FETCH_OK
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#901 Implementations can close the session on any error
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#823 Allow FETCH_ERROR after sending objects
  draft-ietf-moq-transport.md
Labels: Design

#761 Harmonizing serialization of Parameters and Extensions.
  draft-ietf-moq-transport.md
Labels: Parameters, Design

#811 Limit all the things
  draft-ietf-moq-transport.md
Labels: Needs Discussion, Design

#812 Add error codes for resetting data streams
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#917 Change new SETUP points to 0x20/21
  draft-ietf-moq-transport.md
Labels: Editorial, Wire Format

#814 Close on bad PATH
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#921 RESET_STREAM_AT is used, but not required
  draft-ietf-moq-transport.md
Labels: Editorial

#919 Fix inconsistent code points
  draft-ietf-moq-transport.md
Labels: Editorial

#930 Editorial fix in Goaway
  draft-ietf-moq-transport.md
Labels: Editorial

#826 Explain interaction of caching, status and extensions
  draft-ietf-moq-transport.md
Labels: Design

#905 Change Subscription ID to Request ID, add to all requests
  draft-ietf-moq-transport.md
Labels: Design

#827 No extensions for non-existent objects
  draft-ietf-moq-transport.md
Labels: Needs Discussion, Object Model, Design

#927 Clarify how SUBSCRIBE filters work, allow Absolute start before Latest
  draft-ietf-moq-transport.md
Labels: Needs Discussion, Subscribe, Design

#922 Add a mechanism for communicating the size of a Group ID gap
  draft-ietf-moq-transport.md
Labels: Design

#920 Acknowledge QUICR, RUSH and WARP
  draft-ietf-moq-transport.md
Labels: Editorial

#926 Add editorial text on congestion control
  draft-ietf-moq-transport.md
Labels: Editorial

#760 Adding AUTHORIZATION TOKEN parameter
  draft-ietf-moq-transport.md
Labels: Parameters, Design

#941 Message formatting and field name updates.
  draft-ietf-moq-transport.md
Labels: Editorial

#816 Include FETCH responses in priority scheduling algorithm
  draft-ietf-moq-transport.md
Labels: Design

#934 Add Version Negotiation Failed error code
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#957 Clarify behavior of fetch cancel on object delivery.
  draft-ietf-moq-transport.md
Labels: Editorial

#946 Expand cases where FETCH returns Invalid Range
  draft-ietf-moq-transport.md
Labels: Fetch, Editorial & Minor Design

#948 Explain when a relay can reuse or must reset a subgroup
  draft-ietf-moq-transport.md
Labels: Transmission/Priority, Design

#947 Clarify Forward=0 does not affect SUBSCRIBE_DONE
  draft-ietf-moq-transport.md
Labels: Editorial

#956 Address section 9 edits and add common definition for reason phrase
  draft-ietf-moq-transport.md
Labels: Editorial
