Repository moq-wg/moq-transport, pull requests merged in 2025-06, with the labels that each got.

#1032 List what parameters can be repeated in IANA table
  draft-ietf-moq-transport.md
Labels: Editorial

#995 Add a PUBLISH message for publisher initiated subscriptions
  draft-ietf-moq-transport.md
Labels: Design

#1013 Allow AUTHORIZATION TOKEN parameter in CLIENT_SETUP and other Auth fixes
  draft-ietf-moq-transport.md
Labels: Design, Auth

#1051 Third try on PUBLISH code points
  draft-ietf-moq-transport.md
Labels: Editorial
