Repository moq-wg/moq-transport, pull requests merged in 2025-05, with the labels that each got.

#1006 Add type to fetch header
  draft-ietf-moq-transport.md
Labels: Editorial

#972 Use two byte int in all control message definitions
  draft-ietf-moq-transport.md
Labels: Editorial, Wire Format

#990 Include Type field in data stream header descriptions
  draft-ietf-moq-transport.md
Labels: Editorial

#994 Clarifying the QUIC datagram requirement statement.
  draft-ietf-moq-transport.md
Labels: Editorial

#993 Fix order of messages by section numbers
  draft-ietf-moq-transport.md
Labels: Editorial

#987 Fetch should use Joining Request ID instead of subscribe ID
  draft-ietf-moq-transport.md
Labels: Editorial

#980 Use Location for FETCH
  draft-ietf-moq-transport.md
Labels: Editorial

#1020 Minimal Stream definition
  draft-ietf-moq-transport.md
Labels: Editorial

#1024 Remove some temporal language
  draft-ietf-moq-transport.md
Labels: Editorial

#936 Clarify FETCH_OK fields
  draft-ietf-moq-transport.md
Labels: Fetch, Editorial & Minor Design

#977 Move Track Alias from SUBSCRIBE to SUBSCRIBE_OK
  draft-ietf-moq-transport.md
Labels: Subscribe, Design

#1014 Clarify Too Far Behind and DELIVERY TIMEOUT
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#937 Clarify how Latest Object works when the Largest Object is incomplete
  draft-ietf-moq-transport.md
Labels: Design

#825 Add FETCH_ERROR for Unknown Status in Range
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#1011 Allow End of Group to be signaled in a non-zero length object
  draft-ietf-moq-transport.md
Labels: Wire Format, Design

#1017 Relays MUST have upstream subscription to send SUBSCRIBE_OK
  draft-ietf-moq-transport.md
Labels: Design

#992 Reference concept of "time" in 2.3.1
  draft-ietf-moq-transport.md
Labels: Editorial
