Repository moq-wg/moq-transport, pull requests merged in 2025-02, with the labels that each got.

#661 Remove a TODO and obsolete example
  draft-ietf-moq-transport.md
Labels: Editorial

#653 Clarify SUBSCRIBE_UPDATE
  draft-ietf-moq-transport.md
Labels: Editorial

#652 Do not fail SUBSCRIBEs that start in the past
  draft-ietf-moq-transport.md
Labels: Subscribe

#662 Rename SUBGROUP_HEADER_STREAMGROUP to SUBGROUP_HEADER
  draft-ietf-moq-transport.md
Labels: Editorial

#663 Messages are Tag-Length-Value
  draft-ietf-moq-transport.md
Labels: Editorial

#616 Invalid Track Alias/Subscribe ID are a protocol violation
  draft-ietf-moq-transport.md
Labels: Subscribe

#502 Adding an Extensible Object Header
  draft-ietf-moq-transport.md
Labels: Object Model, Wire Format

#638 Joining Fetch
  draft-ietf-moq-transport.md
Labels: Design, Fetch

#696 fix anchor
  draft-ietf-moq-transport.md
Labels: Editorial

#695 fix ref
  draft-ietf-moq-transport.md
Labels: Editorial

#699 fix forwarding preference
  draft-ietf-moq-transport.md
Labels: Editorial

#703 fix message name typo
  draft-ietf-moq-transport.md
Labels: Editorial

#713 Remove Latest Group from SUBSCRIBE
  draft-ietf-moq-transport.md
Labels: Subscribe

#723 Count object extension headers in bytes, not fields
  draft-ietf-moq-transport.md
Labels: Wire Format

#717 Fixes a section name
  draft-ietf-moq-transport.md
Labels: Editorial

#702 proposed change to schedule alg
  draft-ietf-moq-transport.md
Labels: Transmission/Priority

#686 objects are the data model
  draft-ietf-moq-transport.md
Labels: Editorial

#687 Clean up confusing all caps text that seems false
  draft-ietf-moq-transport.md
Labels: Editorial

#734 Define Full Track Name
  draft-ietf-moq-transport.md
Labels: Editorial

#733 Explain Stream Count better
  draft-ietf-moq-transport.md
Labels: Subscribe
