Repository moq-wg/moq-transport, pull requests merged in 2025-03, with the labels that each got.

#753 Remove "and Scope" from a section header
  draft-ietf-moq-transport.md
Labels: Editorial

#751 Move Connection URL section into Session
  draft-ietf-moq-transport.md
Labels: Editorial

#752 Move "Stream Cancellation" into "Data Streams"
  draft-ietf-moq-transport.md
Labels: Editorial

#754 Create a new top-level section for Subscribe and Fetch
  draft-ietf-moq-transport.md
Labels: Editorial

#776 Clarify Parameter Length
  draft-ietf-moq-transport.md
Labels: Editorial

#801 add fetch error for no objects
  draft-ietf-moq-transport.md
Labels: Editorial

#819 Move statement about sequential Object IDs to the Object Model section
  draft-ietf-moq-transport.md
Labels: Editorial, Object Model

#747 Adding Absolute Joining Fetch
  draft-ietf-moq-transport.md
Labels: Fetch

#755 Merge END_OF_TRACK with END_OF_TRACK_AND_GROUP
  draft-ietf-moq-transport.md
Labels: Object Model

#832 Don't call Objects "Messages"
  draft-ietf-moq-transport.md
Labels: Editorial

#831 Update subgroup object fields figure title
  draft-ietf-moq-transport.md
Labels: Editorial

#833 Text descriptions of all error codes
  draft-ietf-moq-transport.md
Labels: Editorial

#828 Explain conflicting Group Order at relay
  draft-ietf-moq-transport.md
Labels: Editorial

#815 Relays can use Latest Object upstream
  draft-ietf-moq-transport.md
Labels: Editorial

#817 Default param values for SUBSCRIBE_UPDATE
  draft-ietf-moq-transport.md
Labels: Design

#829 Remove references to old messages
  draft-ietf-moq-transport.md
Labels: Editorial

#851 Remove reference to HTTP content negotiation
  draft-ietf-moq-transport.md
Labels: Editorial

#854 Add Namespace Prefix Overlap error code
  draft-ietf-moq-transport.md
Labels: Editorial

#857 Remove multiline optional notation from Extensions
  draft-ietf-moq-transport.md
Labels: Editorial

#850 Clarify Group Order in Priority section
  draft-ietf-moq-transport.md
Labels: Editorial

#830 Explain how Control Message length is computed
  draft-ietf-moq-transport.md
Labels: Editorial

#824 Rename FETCH_OK "largest" group/object to "end" and explain
  draft-ietf-moq-transport.md
Labels: Editorial

#858 Introduce a Location structure for Group+Object
  draft-ietf-moq-transport.md
Labels: Editorial

#862 Fix typo
  draft-ietf-moq-transport.md
Labels: Editorial

#875 Remove object ID restriction language
  draft-ietf-moq-transport.md
Labels: Editorial

#866 Minor section 5 edits
  draft-ietf-moq-transport.md
Labels: Editorial

#888 Define "Application" and replace one instance of "Streaming Format"
  draft-ietf-moq-transport.md
Labels: Editorial

#890 Remove the word "routing" from Namespace Discovery section
  draft-ietf-moq-transport.md
Labels: Editorial

#886 Publishers don't discover subscribers
  draft-ietf-moq-transport.md
Labels: Editorial

#793 Groups might not be published in ascending order
  draft-ietf-moq-transport.md
Labels: Editorial, Object Model

#743 Add forward flag to subscribe/subscribe_update
  draft-ietf-moq-transport.md
Labels: Subscribe

#893 Add Alan as Editor, remove Kiril and Luke as authors
  draft-ietf-moq-transport.md
Labels: Editorial

#894 Added Luke Curley and Kirill Pugin to contributors
  draft-ietf-moq-transport.md
Labels: Editorial

#891 Clarify MAX_CACHE_DURATION
  draft-ietf-moq-transport.md
Labels: Editorial

#900 Use consistent requirements for No Objects
  draft-ietf-moq-transport.md
Labels: Editorial
