Repository moq-wg/moq-transport, pull requests merged in 2025-08, with the labels that each got.

#1111 Clarify End of Track
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design, Merge Ready

#1116 Explain Namespace Prefix Matching in more detail
  draft-ietf-moq-transport.md
Labels: Editorial, Merge Ready

#1119 Address miscellaneous Relay section feedback
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design, Merge Ready

#1131 Object Not Exists -> Object Does Not Exist
  draft-ietf-moq-transport.md
Labels: Editorial

#1123 Relay security considerations: SUBSCRIBE_NAMESPACE with short prefix
  draft-ietf-moq-transport.md
Labels: Editorial, Merge Ready

#1106 Add a Request ID to SUBSCRIBE_UDPATE
  draft-ietf-moq-transport.md
Labels: Design, Merge Ready

#1107 Explain Modularity of MOQT
  draft-ietf-moq-transport.md
Labels: Design, Merge Ready

#1143 Misc. editorial changes
  draft-ietf-moq-transport.md
Labels: Editorial, Merge Ready

#1108 RFC: Rename SUBSCRIBE_DONE to PUBLISH_DONE
  draft-ietf-moq-transport.md
Labels: Editorial, Merge Ready

#1114 Add a free-form SETUP parameter identifying the implementation
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design, Merge Ready

#1117 Explain FETCH routing for relays
  draft-ietf-moq-transport.md
Labels: Needs Discussion, Design, Merge Ready

#1166 Minor Edits from #876
  draft-ietf-moq-transport.md
Labels: Editorial

#1115 MUST for multi-publisher relay handling
  draft-ietf-moq-transport.md
Labels: Design
