Repository moq-wg/moq-transport, pull requests merged in 2025-10, with the labels that each got.

#1012 Make expires a parameter
  draft-ietf-moq-transport.md
Labels: Wire Format, Parameters, Design

#1260 Initial proposal warning to not be over zealous in putting in error c…
  draft-ietf-moq-transport.md
Labels: Editorial

#1276 Auth token params have to be unique
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#1277 Disallow DELETE and USE_ALIAS in CLIENT_SETUP
  draft-ietf-moq-transport.md
Labels: Editorial & Minor Design

#1280 Order of Objects in a Group
  draft-ietf-moq-transport.md
Labels: Editorial

#1273 Parameters for Group Order, Subscribe Priority and Subscription Filter (redo)
  draft-ietf-moq-transport.md
Labels: Design

#1060 DYNAMIC_GROUPS and NEW_GROUP_REQUEST parameters
  draft-ietf-moq-transport.md
Labels: Design
